export const SAVE_PASSWORD = 'SAVE_PASSWORD';
export const SAVE_PASSWORD_SUCCESS = 'SAVE_PASSWORD_SUCCESS';
export const SAVE_PASSWORD_FAILURE = 'SAVE_PASSWORD_FAILURE';
export const REPLACE_PASSWORD = 'REPLACE_PASSWORD';
export const CHECK_PASSWORD_VALIDATION = 'CHECK_PASSWORD_VALIDATION';
export const SET_PASSWORD_VALIDATION = 'SET_PASSWORD_VALIDATION';
export const CLEAR_PASSWORD_DATA = 'CLEAR_PASSWORD_DATA';
export const CHECK_IF_PASSWORD_NEEDED = 'CHECK_IF_PASSWORD_NEEDED';
