export const CHECK_IF_METAMASK_EXIST = 'CHECK_IF_METAMASK_EXIST';
export const ENABLE_METAMASK = 'ENABLE_METAMASK';
export const SUBSCRIBE_TO_METAMASK_EVENTS = 'SUBSCRIBE_TO_METAMSK_EVENTS';

export const LOAD_METAMASK_ACCOUNTS = 'LOAD_METAMASK_ACCOUNTS/init';
export const LOAD_METAMASK_ACCOUNTS_SUCCESS = 'LOAD_METAMASK_ACCOUNTS/success';
export const LOAD_METAMASK_ACCOUNTS_FAILURE = 'LOAD_METAMASK_ACCOUNTS/failure';

export const SEND_ETH_FROM_METAMASK = 'SEND_ETH_FROM_METAMASK/init';
export const SEND_ETH_FROM_METAMASK_SUCCESS = 'SEND_ETH_FROM_METAMASK/success';
export const SEND_ETH_FROM_METAMASK_FAILURE = 'SEND_ETH_FROM_METAMASK/failure';
