export const SET_ORGANIZATION_NAME = 'SET_ORGANIZATION_NAME';

export const LOAD_ORGANIZATION = 'LOAD_ORGANIZATION/init';
export const LOAD_ORGANIZATION_SUCCESS = 'LOAD_ORGANIZATION/success';
export const LOAD_ORGANIZATION_FAILURE = 'LOAD_ORGANIZATION/failure';

export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION/init';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION/success';
export const UPDATE_ORGANIZATION_FAILURE = 'UPDATE_ORGANIZATION/failure';

export const LOAD_EVENT_LOGS = 'LOAD_EVENT_LOGS';
export const LOAD_EVENT_LOGS_SUCCESS = 'LOAD_EVENT_LOGS_SUCCESS';
export const LOAD_EVENT_LOGS_FAILURE = 'LOAD_EVENT_LOGS_FAILURE';

export const SHOW_ACTIVE_VALIDATORS_POP_UP = 'SHOW_ACTIVE_VALIDATORS_POP_UP';
