export const LOAD_EVENT_LOGS = 'LOAD_EVENT_LOGS';
export const LOAD_EVENT_LOGS_SUCCESS = 'LOAD_EVENT_LOGS_SUCCESS';
export const LOAD_EVENT_LOGS_FAILURE = 'LOAD_EVENT_LOGS_FAILURE';

export const SHOW_ACTIVE_VALIDATORS_POP_UP = 'SHOW_ACTIVE_VALIDATORS_POP_UP';
