export const TOGGLE_REACTIVATION_MODAL_DISPLAY = 'TOGGLE_REACTIVATION_MODAL_DISPLAY';
export const TOGGLE_UPDATE_MODAL_DISPLAY = 'TOGGLE_UPDATE_MODAL_DISPLAY';
export const TOGGLE_DEPOSIT_INFO_MODAL_DISPLAY = 'TOGGLE_DEPOSIT_INFO_MODAL_DISPLAY';
