export const KEYVAULT_SET_COLUD_PROVIDER = 'KEYVAULT/setCloudProvider';

export const KEYVAULT_LOAD_MNEMONIC = 'KEYVAULT_LOAD_MNEMONIC/init';
export const KEYVAULT_LOAD_MNEMONIC_SUCCESS = 'KEYVAULT_LOAD_MNEMONIC/success';
export const KEYVAULT_LOAD_MNEMONIC_FAILURE = 'KEYVAULT_LOAD_MNEMONIC/failure';

export const KEYVAULT_SAVE_MNEMONIC = 'KEYVAULT_SAVE_MNEMONIC/init';
export const KEYVAULT_SAVE_MNEMONIC_SUCCESS = 'KEYVAULT_SAVE_MNEMONIC/success';
export const KEYVAULT_SAVE_MNEMONIC_FAILURE = 'KEYVAULT_SAVE_MNEMONIC/failure';

export const KEYVAULT_LOAD_LATEST_VERSION = 'KEYVAULT_LOAD_LATEST_VERSION/init';
export const KEYVAULT_LOAD_LATEST_VERSION_SUCCESS = 'KEYVAULT_LOAD_LATEST_VERSION/success';
export const KEYVAULT_LOAD_LATEST_VERSION_FAILURE = 'KEYVAULT_LOAD_LATEST_VERSION/failure';

export const KEYVAULT_SAVE_PASSWORD = 'KEYVAULT_SAVE_PASSWORD';
export const KEYVAULT_REPLACE_PASSWORD = 'KEYVAULT_REPLACE_PASSWORD';
export const KEYVAULT_VALIDATE_PASSWORD = 'KEYVAULT_VALIDATE_PASSWORD';

export const KEYVAULT_CLEAR_DATA = 'KEYVAULT_CLEAR_DATA';
