export const KEYVAULT_INSTALL = 'KEYVAULT_INSTALL/init';
export const KEYVAULT_SUCCESS = 'KEYVAULT_INSTALL/success';
export const KEYVAULT_FAILURE = 'KEYVAULT_INSTALL/failure';

export const KEYVAULT_INSTALL_SET_OTP = 'KEYVAULT_INSTALL/setOtp';
export const KEYVAULT_INSTALL_SET_CREDENTIALS = 'KEYVAULT_INSTALL/setCredentials';
export const KEYVAULT_INSTALL_SUBSCRIBE = 'KEYVAULT_INSTALL/subscribe';
