export const KEYVAULT_SET_COLUD_PROVIDER = 'KEYVAULT/setCloudProvider';

export const KEYVAULT_LOAD_MNEMONIC = 'KEYVAULT_LOAD_MNEMONIC/init';
export const KEYVAULT_LOAD_MNEMONIC_SUCCESS = 'KEYVAULT_LOAD_MNEMONIC/success';
export const KEYVAULT_LOAD_MNEMONIC_FAILURE = 'KEYVAULT_LOAD_MNEMONIC/failure';

export const KEYVAULT_SAVE_MNEMONIC = 'KEYVAULT_SAVE_MNEMONIC/init';
export const KEYVAULT_SAVE_MNEMONIC_SUCCESS = 'KEYVAULT_SAVE_MNEMONIC/success';
export const KEYVAULT_SAVE_MNEMONIC_FAILURE = 'KEYVAULT_SAVE_MNEMONIC/failure';
