export const LOAD_BLOX_LIVE_VERSION = 'LOAD_BLOX_LIVE_VERSION/init';
export const LOAD_BLOX_LIVE_VERSION_SUCCESS = 'LOAD_BLOX_LIVE_VERSION_SUCCESS/success';
export const LOAD_BLOX_LIVE_VERSION_FAILURE = 'LOAD_BLOX_LIVE_VERSION_FAILURE/failure';
