export const LOAD_WALLET = 'LOAD_WALLET/init';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET/success';
export const LOAD_WALLET_FAILURE = 'LOAD_WALLET/failure';

export const SET_NETWORK_TYPE = 'SET_NETWORK_TYPE';

export const LOAD_DEPOSIT_DATA = 'LOAD_DEPOSIT_DATA/init';
export const LOAD_DEPOSIT_DATA_SUCCESS = 'LOAD_DEPOSIT_DATA/success';
export const LOAD_DEPOSIT_DATA_FAILURE = 'LOAD_DEPOSIT_DATA/failure';

export const SET_FINISHED_WIZARD = 'SET_FINISHED_WIZARD';
