export const LOAD_WALLET = 'LOAD_WALLET/init';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET/success';
export const LOAD_WALLET_FAILURE = 'LOAD_WALLET/failure';

export const SET_NETWORK_TYPE = 'SET_NETWORK_TYPE';

export const GENERATE_VALIDATOR_KEY = 'GENERATE_VALIDATOR_KEY/init';
export const GENERATE_VALIDATOR_KEY_SUCCESS = 'GENERATE_VALIDATOR_KEY/success';
export const GENERATE_VALIDATOR_KEY_FAILURE = 'GENERATE_VALIDATOR_KEY/failure';

export const LOAD_DEPOSIT_DATA = 'LOAD_DEPOSIT_DATA/init';
export const LOAD_DEPOSIT_DATA_SUCCESS = 'LOAD_DEPOSIT_DATA/success';
export const LOAD_DEPOSIT_DATA_FAILURE = 'LOAD_DEPOSIT_DATA/failure';
export const LOAD_DEPOSIT_DATA_CLEAR = 'LOAD_DEPOSIT_DATA/clear';

export const UPDATE_ACCOUNT_STATUS = 'UPDATE_ACCOUNT_STATUS/init';
export const UPDATE_ACCOUNT_STATUS_SUCCESS = 'UPDATE_ACCOUNT_STATUS/success';
export const UPDATE_ACCOUNT_STATUS_FAILURE = 'UPDATE_ACCOUNT_STATUS/failure';

export const SET_FINISHED_WIZARD = 'SET_FINISHED_WIZARD';

export const CLEAR_DATA = 'WIZARD/clear_data';
