export const CREATE_ONE_TIME_PASS = 'CREATE_ONE_TIME_PASS/init';
export const CREATE_ONE_TIME_PASS_SUCCESS = 'CREATE_ONE_TIME_PASS/success';
export const CREATE_ONE_TIME_PASS_FAILURE = 'CREATE_ONE_TIME_PASS/failure';

export const LOAD_WALLET = 'LOAD_WALLET/init';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET/success';
export const LOAD_WALLET_FAILURE = 'LOAD_WALLET/failure';

export const SET_NETWORK_TYPE = 'SET_NETWORK_TYPE';

export const GENERATE_VALIDATOR_KEY = 'GENERATE_VALIDATOR_KEY/init';
export const GENERATE_VALIDATOR_KEY_SUCCESS = 'GENERATE_VALIDATOR_KEY/success';
export const GENERATE_VALIDATOR_KEY_FAILURE = 'GENERATE_VALIDATOR_KEY/failure';

export const LOAD_DEPOSIT_DATA = 'LOAD_DEPOSIT_DATA/init';
export const LOAD_DEPOSIT_DATA_SUCCESS = 'LOAD_DEPOSIT_DATA/success';
export const LOAD_DEPOSIT_DATA_FAILURE = 'LOAD_DEPOSIT_DATA/failure';

export const SET_FINISHED_WIZARD = 'SET_FINISHED_WIZARD';
